/**
 * PostgreSQL schema extraction mappers.
 * Design §map.ts "rows → deterministic sorted RawCatalog".
 *
 * buildPgRawCatalog(input, scope) assembles a deterministic RawCatalog from
 * pre-fetched pg_catalog row arrays (testable with JSON fixtures — no live DB here).
 *
 * Determinism (ADR-008):
 *   - objects  : sorted by (KIND_RANK, schema, name) — mirrors mssql/map.ts
 *   - columns  : by attnum (ordinal)
 *   - constraints: by name (sorted alphabetically)
 *   - FK/index columns: by array ordinal (conkey / indkey position)
 *   - trigger events: grouped by trigger name, decoded from tgtype bitmask
 *   - schemas  : distinct-sorted from all extracted object schema fields
 *
 * Materialized views → { kind: 'view', extra: { materialized: true } }
 * NO new NodeKind introduced (US-028b).
 *
 * Edges from bodies via tokenizePgBody at confidence:'parsed' (no score).
 * supportsDependencyHints: false (body tokenizer is the SOLE edge source).
 *
 * US-028 (PostgreSQL adapter), US-028b (matview without model change),
 * US-007 (reads_from/writes_to classification), ADR-008 (determinism).
 */

import type { ExtractionScope } from '../../../core/model/capability.js';
import type {
  RawCatalog,
  RawObject,
  RawColumn,
  RawConstraint,
  RawIndex,
  RawTriggerInfo,
  RawDependency,
  RawParameter,
} from '../../../core/model/catalog.js';
import type { NodeKind } from '../../../core/model/node.js';
import { tokenizePgBody } from './tokenizer.js';

// ─────────────────────────────────────────────────────────────────────────────
// Kind rank for deterministic ordering (mirrors mssql/map.ts KIND_RANK)
// ─────────────────────────────────────────────────────────────────────────────

const KIND_RANK: Record<NodeKind, number> = {
  database: 0,
  schema: 1,
  table: 2,
  view: 3,
  trigger: 4,
  column: 5,
  constraint: 6,
  index: 7,
  procedure: 8,
  function: 9,
  sequence: 10,
  collection: 11,
  field: 12,
};

function kindRank(k: NodeKind): number {
  return KIND_RANK[k] ?? 99;
}

function compareObjects(a: RawObject, b: RawObject): number {
  const rankDiff = kindRank(a.kind) - kindRank(b.kind);
  if (rankDiff !== 0) return rankDiff;
  const schemaDiff = (a.schema ?? '').localeCompare(b.schema ?? '');
  if (schemaDiff !== 0) return schemaDiff;
  return a.name.localeCompare(b.name);
}

// ─────────────────────────────────────────────────────────────────────────────
// Row shape interfaces (matching query output from queries.ts)
// ─────────────────────────────────────────────────────────────────────────────

export interface SchemaRow {
  readonly schema_name: string;
}

export interface TableRow {
  readonly schema_name: string;
  readonly table_name: string;
  readonly table_oid: number;
  readonly comment: string | null;
}

export interface ColumnRow {
  readonly schema_name: string;
  readonly table_name: string;
  readonly ordinal: number;
  readonly column_name: string;
  readonly data_type: string;
  readonly is_nullable: boolean;
  readonly default_expr: string | null;
  /** 'a' = GENERATED ALWAYS AS IDENTITY, 'd' = GENERATED BY DEFAULT AS IDENTITY, '' = not identity */
  readonly identity_kind: string;
  /** 's' = GENERATED ALWAYS AS (...) STORED, '' = not generated */
  readonly generated_kind: string;
  readonly comment: string | null;
}

export interface ColumnNameRow {
  readonly schema_name: string;
  readonly table_name: string;
  readonly table_oid: number;
  readonly attnum: number;
  readonly column_name: string;
}

export interface ConstraintRow {
  readonly schema_name: string;
  readonly table_name: string;
  readonly constraint_name: string;
  /** 'p'=PK, 'f'=FK, 'u'=UNIQUE, 'c'=CHECK */
  readonly constraint_type: string;
  /** Integer array of column attnums for this constraint (may be null for CHECK) */
  readonly column_positions: readonly number[] | null;
  /** Integer array of referenced column attnums (FK only) */
  readonly fk_ref_positions: readonly number[] | null;
  readonly fk_ref_schema: string | null;
  readonly fk_ref_table: string | null;
  readonly constraint_def: string | null;
}

export interface IndexRow {
  readonly schema_name: string;
  readonly table_name: string;
  readonly index_name: string;
  readonly is_unique: boolean;
  readonly is_primary: boolean;
  /** indkey int[] — all column attnums including non-key INCLUDE columns; 0 = expression column */
  readonly key_columns: readonly number[];
  /** indnkeyatts — number of KEY columns; remaining entries in key_columns are INCLUDE non-key columns */
  readonly n_key_atts: number;
  readonly index_def: string;
}

export interface ViewRow {
  readonly schema_name: string;
  readonly view_name: string;
  /** 'v' = regular view, 'm' = materialized view */
  readonly rel_kind: string;
  readonly view_def: string | null;
  readonly comment: string | null;
}

export interface RoutineRow {
  readonly schema_name: string;
  readonly routine_name: string;
  /** 'f' = function, 'p' = procedure */
  readonly routine_kind: string;
  readonly routine_def: string | null;
  readonly comment: string | null;
  // DOG-2 §4.2: argument arrays decoded inline on the pg_proc row (all index-aligned).
  // OPTIONAL so pre-DOG-2 fixtures without them stay valid — when arg_type_names is absent
  // the routine leaves parameters UNSET (unknown), NOT [] (known-zero). node-postgres parses
  // text[]/regtype[]::text[] into JS arrays; proargnames may carry nulls for unnamed positions.
  readonly arg_names?: readonly (string | null)[] | null;   // proargnames — NULL when all unnamed
  readonly arg_modes?: readonly string[] | null;            // proargmodes::text[] — NULL ⇒ all IN
  readonly arg_type_names?: readonly string[] | null;       // regtype[]::text[] — typmod-less
  readonly num_defaults?: number | null;                    // pronargdefaults — trailing defaults
}

export interface TriggerRow {
  readonly schema_name: string;
  readonly table_name: string;
  readonly trigger_name: string;
  /**
   * tgtype bitmask:
   *   bit 0 (1)  : ROW-level (set) vs STATEMENT-level (clear)
   *   bit 1 (2)  : BEFORE (set) / AFTER (clear)
   *   bit 2 (4)  : INSERT
   *   bit 3 (8)  : DELETE
   *   bit 4 (16) : UPDATE
   *   bit 5 (32) : TRUNCATE
   *   bit 6 (64) : INSTEAD OF
   */
  readonly tgtype: number;
  readonly function_oid: number;
  readonly function_schema_class: string | null;
  readonly function_schema: string;
  readonly function_name: string;
  readonly trigger_def: string | null;
}

export interface SequenceRow {
  readonly schema_name: string;
  readonly sequence_name: string;
  readonly start_value: string;
  readonly increment: string;
  readonly minimum_value: string;
  readonly maximum_value: string;
  readonly is_cycling: boolean;
  readonly comment: string | null;
}

/**
 * One row of `information_schema.view_column_usage` (DOG-3 design D5): a single (view, source
 * table, source column) triple. Unlike the mssql per-view TVF loop, the pg catalog view already
 * returns ALL view rows in ONE query — no per-object loop, no per-call error handling needed
 * (a plain catalog SELECT either succeeds or the whole extract() call fails, same as every
 * other pg query). Materialized-view rows and owner-invisible-source rows are STRUCTURALLY
 * ABSENT from this result (the catalog itself omits them) — map.ts merges ONLY what is present.
 */
export interface ViewColumnUsageRow {
  readonly view_schema: string;
  readonly view_name: string;
  readonly table_schema: string;
  readonly table_name: string;
  readonly column_name: string;
}

/**
 * Full set of pre-fetched pg_catalog row arrays passed to buildPgRawCatalog.
 * In production: populated by the adapter from PgReadonlyDriver queries.
 * In tests: populated directly from JSON fixtures (no live DB).
 */
export interface PgRowInput {
  readonly schemas: readonly SchemaRow[];
  readonly tables: readonly TableRow[];
  readonly columns: readonly ColumnRow[];
  readonly columnNames: readonly ColumnNameRow[];
  readonly constraints: readonly ConstraintRow[];
  readonly indexes: readonly IndexRow[];
  readonly views: readonly ViewRow[];
  readonly routines: readonly RoutineRow[];
  readonly triggers: readonly TriggerRow[];
  readonly sequences: readonly SequenceRow[];
  // DOG-3 (design D5): flat `information_schema.view_column_usage` rows. OPTIONAL — pre-DOG-3
  // fixtures/callers leave it UNSET, so every view dep stays object grain BYTE-IDENTICAL. When
  // present, buildViews merges it onto each covered view dependency `columns` and flips that
  // dependency to `confidence: 'declared'`.
  readonly viewColumnUsage?: readonly ViewColumnUsageRow[];
}

// ─────────────────────────────────────────────────────────────────────────────
// tgtype bitmask decoder
// ─────────────────────────────────────────────────────────────────────────────

function decodeTgType(tgtype: number): {
  timing: 'BEFORE' | 'AFTER' | 'INSTEAD OF';
  events: ('INSERT' | 'UPDATE' | 'DELETE')[];
} {
  // bit 6 (64): INSTEAD OF
  if ((tgtype & 64) !== 0) {
    const events: ('INSERT' | 'UPDATE' | 'DELETE')[] = [];
    if ((tgtype & 4) !== 0)  events.push('INSERT');
    if ((tgtype & 16) !== 0) events.push('UPDATE');
    if ((tgtype & 8) !== 0)  events.push('DELETE');
    return { timing: 'INSTEAD OF', events };
  }

  // bit 1 (2): BEFORE (set) / AFTER (clear)
  const timing: 'BEFORE' | 'AFTER' = (tgtype & 2) !== 0 ? 'BEFORE' : 'AFTER';

  const events: ('INSERT' | 'UPDATE' | 'DELETE')[] = [];
  if ((tgtype & 4) !== 0)  events.push('INSERT');
  if ((tgtype & 16) !== 0) events.push('UPDATE');
  if ((tgtype & 8) !== 0)  events.push('DELETE');

  return { timing, events };
}

// ─────────────────────────────────────────────────────────────────────────────
// Column name lookup map (oid + attnum → column_name)
// ─────────────────────────────────────────────────────────────────────────────

function buildColumnNameMap(rows: readonly ColumnNameRow[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const row of rows) {
    map.set(`${row.table_oid}:${row.attnum}`, row.column_name);
    map.set(`${row.schema_name}.${row.table_name}:${row.attnum}`, row.column_name);
  }
  return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper — table key
// ─────────────────────────────────────────────────────────────────────────────

function tableKey(schema: string, name: string): string {
  return `${schema}.${name}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// DOG-3 (D4/D5): group view_column_usage rows and merge onto covered view deps
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Coerces flat `information_schema.view_column_usage` rows into a `view qname` → `target table
 * qname` → ordered-unique `Set` of consumed source columns. A materialized view or an
 * owner-invisible source is simply ABSENT from `rows` (a real catalog fact), so it never gets a
 * group here — the caller lookup naturally misses and the dependency stays object grain
 * (degrade-by-absence, D4). Insertion order follows the query ORDER BY (ADR-008 stable); the
 * normalizer re-sorts code-point ascending for the edge attr (D3), so this does NOT sort.
 * Exported for the B.1 recorded-rows shape test.
 */
export function groupViewColumnUsage(
  rows: readonly ViewColumnUsageRow[],
): Map<string, Map<string, Set<string>>> {
  const groups = new Map<string, Map<string, Set<string>>>();
  for (const r of rows) {
    const viewKey = tableKey(r.view_schema, r.view_name);
    const targetKey = tableKey(r.table_schema, r.table_name);
    let byTarget = groups.get(viewKey);
    if (byTarget === undefined) {
      byTarget = new Map();
      groups.set(viewKey, byTarget);
    }
    let cols = byTarget.get(targetKey);
    if (cols === undefined) {
      cols = new Set();
      byTarget.set(targetKey, cols);
    }
    cols.add(r.column_name);
  }
  return groups;
}

/**
 * Enriches a view tokenizer-derived `RawDependency` list with the source columns
 * `view_column_usage` attributed to each COVERED (view, table) pair. A covered dep GAINS
 * `columns` and FLIPS to `confidence: 'declared'` (a catalog-confirmed pair IS declared, D5); an
 * uncovered dep (materialized view / owner-visibility gap / any source the catalog omits) is
 * returned UNCHANGED — object grain, `columns` UNSET, still `parsed` (degrade-by-absence, D4).
 * NEVER fabricates a column from the body.
 */
function enrichViewDeps(
  deps: readonly RawDependency[],
  viewSchema: string,
  viewName: string,
  viewColumnGroups: ReadonlyMap<string, ReadonlyMap<string, ReadonlySet<string>>>,
): readonly RawDependency[] {
  const byTarget = viewColumnGroups.get(tableKey(viewSchema, viewName));
  if (byTarget === undefined || byTarget.size === 0) return deps;
  return deps.map((dep) => {
    const cols = byTarget.get(tableKey(dep.target.schema ?? '', dep.target.name));
    if (cols === undefined || cols.size === 0) return dep;
    return { ...dep, confidence: 'declared' as const, columns: Array.from(cols) };
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Column mapping
// ─────────────────────────────────────────────────────────────────────────────

type ExtendedRawColumn = RawColumn & { extra?: Readonly<Record<string, unknown>> };

function buildColumns(
  schema: string,
  tableName: string,
  allColumns: readonly ColumnRow[],
): ExtendedRawColumn[] {
  const key = tableKey(schema, tableName);
  return allColumns
    .filter((c) => tableKey(c.schema_name, c.table_name) === key)
    .sort((a, b) => a.ordinal - b.ordinal)
    .map((c) => {
      // Identity column extra
      let extra: Readonly<Record<string, unknown>> | undefined;
      if (c.identity_kind === 'a' || c.identity_kind === 'd') {
        extra = {
          identity: true,
          identityKind: c.identity_kind === 'a' ? 'ALWAYS' : 'BY_DEFAULT',
        };
      } else if (c.generated_kind === 's') {
        extra = { generated: true };
      }

      const col: ExtendedRawColumn = {
        name: c.column_name,
        dataType: c.data_type,
        nullable: c.is_nullable,
        ordinal: c.ordinal,
        ...(c.default_expr !== null ? { default: c.default_expr } : {}),
        ...(c.comment !== null ? { comment: c.comment } : {}),
        ...(extra !== undefined ? { extra } : {}),
      };
      return col;
    });
}

// ─────────────────────────────────────────────────────────────────────────────
// Constraint mapping
// ─────────────────────────────────────────────────────────────────────────────

function buildConstraints(
  schema: string,
  tableName: string,
  rows: readonly ConstraintRow[],
  tableOid: number,
  columnNameMap: Map<string, string>,
): RawConstraint[] {
  const key = tableKey(schema, tableName);
  const filtered = rows.filter((r) => tableKey(r.schema_name, r.table_name) === key);

  return filtered
    .sort((a, b) => a.constraint_name.localeCompare(b.constraint_name))
    .flatMap((row): RawConstraint[] => {
      const colPositions = row.column_positions ?? [];

      switch (row.constraint_type) {
        case 'p': {
          // PK
          const columns = colPositions.map(
            (pos) => columnNameMap.get(`${tableOid}:${pos}`) ?? columnNameMap.get(`${key}:${pos}`) ?? `col_${pos}`
          );
          return [{
            name: row.constraint_name,
            type: 'PK',
            columns,
          }];
        }
        case 'u': {
          // UNIQUE
          const columns = colPositions.map(
            (pos) => columnNameMap.get(`${tableOid}:${pos}`) ?? columnNameMap.get(`${key}:${pos}`) ?? `col_${pos}`
          );
          return [{
            name: row.constraint_name,
            type: 'UNIQUE',
            columns,
          }];
        }
        case 'f': {
          // FK — columns + ref columns by array ordinal
          const localCols = (row.column_positions ?? []).map(
            (pos) => columnNameMap.get(`${tableOid}:${pos}`) ?? columnNameMap.get(`${key}:${pos}`) ?? `col_${pos}`
          );
          // For FK ref columns, look up by the ref table oid+attnum.
          // The ref table oid is not available in the constraint row,
          // we use the column_names lookup by schema.table:attnum.
          const refTableKey = row.fk_ref_schema && row.fk_ref_table
            ? tableKey(row.fk_ref_schema, row.fk_ref_table)
            : null;
          const refCols = (row.fk_ref_positions ?? []).map((pos) => {
            if (refTableKey) {
              return columnNameMap.get(`${refTableKey}:${pos}`) ?? `col_${pos}`;
            }
            return `col_${pos}`;
          });
          return [{
            name: row.constraint_name,
            type: 'FK',
            columns: localCols,
            references: {
              schema: row.fk_ref_schema,
              table: row.fk_ref_table ?? '',
              columns: refCols,
            },
          }];
        }
        case 'c': {
          // CHECK
          return [{
            name: row.constraint_name,
            type: 'CHECK',
            columns: [],
            ...(row.constraint_def !== null ? { definition: row.constraint_def } : {}),
          }];
        }
        default:
          return [];
      }
    });
}

// ─────────────────────────────────────────────────────────────────────────────
// Index mapping
// ─────────────────────────────────────────────────────────────────────────────

function buildIndexes(
  schema: string,
  tableName: string,
  rows: readonly IndexRow[],
  tableOid: number,
  columnNameMap: Map<string, string>,
): (RawIndex & { extra?: Record<string, unknown> })[] {
  const key = tableKey(schema, tableName);
  return rows
    .filter((r) => tableKey(r.schema_name, r.table_name) === key && !r.is_primary)
    .sort((a, b) => a.index_name.localeCompare(b.index_name))
    .map((row) => {
      const allPositions = row.key_columns;
      const nKey = row.n_key_atts;

      // Positions 0..nKey-1 are key columns; positions nKey..end are INCLUDE non-key columns.
      const keyPositions = allPositions.slice(0, nKey);
      const includePositions = allPositions.slice(nKey);

      // Detect expression index: any key position is 0 (pg_index sentinel for expression)
      const isExpression = keyPositions.some((p) => p === 0);

      // Key column names (skip 0-positions since they are expressions)
      const keyColumns = keyPositions
        .filter((pos) => pos !== 0)
        .map((pos) => {
          return columnNameMap.get(`${tableOid}:${pos}`)
            ?? columnNameMap.get(`${key}:${pos}`)
            ?? `col_${pos}`;
        });

      // Included column names
      const includedColumns = includePositions
        .filter((pos) => pos !== 0)
        .map((pos) => {
          return columnNameMap.get(`${tableOid}:${pos}`)
            ?? columnNameMap.get(`${key}:${pos}`)
            ?? `col_${pos}`;
        });

      // Extract WHERE predicate from index_def (partial index)
      const whereMatch = /\bWHERE\b(.+)$/i.exec(row.index_def);
      const whereClause = whereMatch?.[1]?.trim() ?? null;

      const extra: Record<string, unknown> = {};
      if (whereClause !== null) {
        extra['where'] = whereClause;
      }
      if (isExpression) {
        extra['isExpression'] = true;
        // Also store the full definition so callers can inspect the expression
        extra['indexDef'] = row.index_def;
      }
      if (includedColumns.length > 0) {
        extra['includedColumns'] = includedColumns;
      }

      const idx: RawIndex & { extra?: Record<string, unknown> } = {
        name: row.index_name,
        unique: row.is_unique,
        columns: keyColumns,
        ...(Object.keys(extra).length > 0 ? { extra } : {}),
      };
      return idx;
    });
}

// ─────────────────────────────────────────────────────────────────────────────
// Table extraction
// ─────────────────────────────────────────────────────────────────────────────

function buildTables(
  input: PgRowInput,
  scope: ExtractionScope,
  columnNameMap: Map<string, string>,
): RawObject[] {
  if (scope.levels.tables === 'off') return [];

  return input.tables.map((tableRow) => {
    const columns = buildColumns(tableRow.schema_name, tableRow.table_name, input.columns);
    const constraints = buildConstraints(
      tableRow.schema_name,
      tableRow.table_name,
      input.constraints,
      tableRow.table_oid,
      columnNameMap,
    );
    const indexes = buildIndexes(
      tableRow.schema_name,
      tableRow.table_name,
      input.indexes,
      tableRow.table_oid,
      columnNameMap,
    );

    const obj: RawObject = {
      kind: 'table',
      schema: tableRow.schema_name,
      name: tableRow.table_name,
      columns: columns as RawColumn[],
      constraints,
      indexes: indexes as RawIndex[],
      ...(tableRow.comment !== null ? { comment: tableRow.comment } : {}),
    };
    return obj;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// View extraction (views + materialized views)
// ─────────────────────────────────────────────────────────────────────────────

function buildViews(
  input: PgRowInput,
  scope: ExtractionScope,
  potentialDeps: readonly { schema: string; name: string }[],
  viewColumnGroups: ReadonlyMap<string, ReadonlyMap<string, ReadonlySet<string>>>,
): RawObject[] {
  const level = scope.levels.views;
  if (level === 'off') return [];

  const includeBody = level === 'full';

  return input.views.map((viewRow): RawObject => {
    const isMaterialized = viewRow.rel_kind === 'm';
    const body = includeBody ? (viewRow.view_def ?? undefined) : undefined;

    // Classify dependencies from the view body (reads_from base tables)
    let dependencies: readonly RawDependency[] | undefined;
    if (includeBody && body !== undefined) {
      // For views, there are no catalog-supplied deps (supportsDependencyHints=false).
      // Pass all known tables/views as potential deps; tokenizePgBody classifies each
      // as read or write by scanning the body.
      const result = tokenizePgBody(body, potentialDeps);
      if (result.dependencies.length > 0) {
        // DOG-3 (D5): merge information_schema.view_column_usage onto the covered pairs (flip
        // to declared + attach columns). Materialized views / owner-gap sources are naturally
        // absent from viewColumnGroups → returned UNCHANGED (degrade-by-absence, D4).
        dependencies = enrichViewDeps(result.dependencies, viewRow.schema_name, viewRow.view_name, viewColumnGroups);
      }
    }

    const obj: RawObject = {
      kind: 'view',
      schema: viewRow.schema_name,
      name: viewRow.view_name,
      ...(body !== undefined ? { body } : {}),
      ...(isMaterialized ? { extra: { materialized: true } } : {}),
      ...(viewRow.comment !== null ? { comment: viewRow.comment } : {}),
      ...(dependencies !== undefined && dependencies.length > 0 ? { dependencies } : {}),
    };
    return obj;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Routine extraction (functions + procedures)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Decodes pg_proc argument arrays (index-aligned) into ordinal-ordered RawParameter[].
 * DOG-2 §4.2 / D5 / D6. Returns undefined when the row carries NO arg-type array (pre-DOG-2
 * fixture / unknown) — honest absence, "unknown" ≠ "known-zero"; a real no-arg routine has an
 * EMPTY arg_type_names array and yields [].
 *
 * Rules (per element i, aligned across arg_type_names / arg_modes / arg_names):
 *   - mode: i→in, o→out, b→inout, v (VARIADIC)→in, t (RETURNS TABLE)→EXCLUDED (result column).
 *     arg_modes NULL ⇒ EVERY arg is 'in' (the all-IN encoding) — NEVER fabricate out/inout.
 *   - dataType: the regtype name VERBATIM (typmod-less; numeric, never numeric(10,2)).
 *   - ordinal: contiguous 1..N over EMITTED args (after excluding any t-mode entry).
 *   - hasDefault: only the TRAILING num_defaults INPUT-capable (non-out) emitted args — pg
 *     exposes the count, not per-arg flags, so we never over-claim.
 */
function decodePgParameters(row: RoutineRow): readonly RawParameter[] | undefined {
  const typeNames = row.arg_type_names;
  if (typeNames === undefined || typeNames === null) return undefined; // unknown → UNSET

  const modes = row.arg_modes ?? null; // null ⇒ all 'in'
  const names = row.arg_names ?? null;

  const params: RawParameter[] = [];
  for (let i = 0; i < typeNames.length; i++) {
    const mode = modes !== null ? modes[i] : 'i';
    if (mode === 't') continue; // RETURNS TABLE result column — not a call parameter
    const direction: RawParameter['direction'] =
      mode === 'o' ? 'out' : mode === 'b' ? 'inout' : 'in'; // i / v / null / anything else → in
    const rawName = names !== null ? names[i] : null;
    params.push({
      name: rawName ?? '',
      dataType: typeNames[i] ?? '',
      direction,
      ordinal: params.length + 1,
    });
  }

  // hasDefault: mark the trailing num_defaults INPUT-capable (direction !== 'out') emitted args.
  const numDefaults = row.num_defaults ?? 0;
  if (numDefaults > 0) {
    const inputIdx = params
      .map((p, idx) => ({ p, idx }))
      .filter(({ p }) => p.direction !== 'out')
      .map(({ idx }) => idx);
    for (const idx of inputIdx.slice(Math.max(0, inputIdx.length - numDefaults))) {
      params[idx] = { ...params[idx]!, hasDefault: true };
    }
  }

  return params;
}

function buildRoutines(
  input: PgRowInput,
  scope: ExtractionScope,
): RawObject[] {
  const objects: RawObject[] = [];

  for (const row of input.routines) {
    const kind: NodeKind = row.routine_kind === 'p' ? 'procedure' : 'function';

    let level: 'off' | 'metadata' | 'full';
    if (kind === 'function') {
      level = scope.levels.functions;
    } else {
      level = scope.levels.procedures;
    }
    if (level === 'off') continue;

    const includeBody = level === 'full';
    const body = includeBody ? (row.routine_def ?? undefined) : undefined;

    // Classify dependencies from the routine body
    let dependencies: readonly RawDependency[] | undefined;
    let hasDynSql: boolean | undefined;

    if (includeBody && body !== undefined) {
      // We need to know what objects this routine might reference.
      // No catalog-supplied deps are available (supportsDependencyHints=false),
      // we pass known objects as potential deps and let the tokenizer classify them.
      //
      // DOG-1 (D3/D4): the candidate list is EXTENDED with ROUTINE nodes (carrying `kind`)
      // so a `SELECT fn()` / `PERFORM fn()` / `CALL proc()` resolves to a `calls` edge.
      // The current routine is EXPLICITLY self-excluded — `pg_get_functiondef` emits the
      // full `CREATE FUNCTION app.fn_x(...)` header, so the body contains its OWN qname;
      // without this filter a routine would `calls` itself.
      const routineCandidates = input.routines
        .filter((r) => !(r.schema_name === row.schema_name && r.routine_name === row.routine_name))
        .map((r) => ({
          schema: r.schema_name,
          name: r.routine_name,
          kind: (r.routine_kind === 'p' ? 'procedure' : 'function') as 'procedure' | 'function',
        }));
      const potentialDeps = [
        ...input.tables.map((t) => ({ schema: t.schema_name, name: t.table_name })),
        ...input.views.map((v) => ({ schema: v.schema_name, name: v.view_name })),
        ...routineCandidates,
      ];
      const result = tokenizePgBody(body, potentialDeps);
      // WARNING-1 FIX: static edges SURVIVE even when hasDynamicSql is true.
      // tokenizePgBody already masks string-literal contents so only static
      // references generate edges (CRITICAL-1 fix). Dynamic SQL is flagged via
      // hasDynamicSql:true; the static portion is still classified and emitted.
      // This makes PG consistent with MSSQL (which keeps catalog-confirmed static
      // edges alongside hasDynamicSql:true). ADR-007 / US-007.
      if (result.hasDynamicSql) {
        hasDynSql = true;
      }
      if (result.dependencies.length > 0) {
        dependencies = result.dependencies;
      }
    }

    // DOG-2 §4.2/D6: decode inline pg_proc arg arrays into ordinal-ordered parameters.
    // undefined (no arg arrays on the row) ⇒ leave the field UNSET (honest absence).
    const parameters = decodePgParameters(row);

    const obj: RawObject = {
      kind,
      schema: row.schema_name,
      name: row.routine_name,
      ...(body !== undefined ? { body } : {}),
      ...(hasDynSql !== undefined ? { hasDynamicSql: hasDynSql } : {}),
      ...(dependencies !== undefined && dependencies.length > 0 ? { dependencies } : {}),
      ...(parameters !== undefined ? { parameters } : {}),
      ...(row.comment !== null ? { comment: row.comment } : {}),
    };
    objects.push(obj);
  }

  return objects;
}

// ─────────────────────────────────────────────────────────────────────────────
// Trigger extraction
// ─────────────────────────────────────────────────────────────────────────────

function buildTriggers(
  input: PgRowInput,
  scope: ExtractionScope,
): RawObject[] {
  const level = scope.levels.triggers;
  if (level === 'off') return [];

  const includeBody = level === 'full';

  return input.triggers.map((row): RawObject => {
    const { timing, events } = decodeTgType(row.tgtype);

    const triggerInfo: RawTriggerInfo = {
      timing,
      events,
      table: { schema: row.schema_name, name: row.table_name },
    };

    // Body for a trigger is the trigger_def (CREATE TRIGGER statement).
    // hasDynamicSql is checked on the FUNCTION body (not the trigger DDL itself),
    // because the trigger DDL will always contain EXECUTE FUNCTION which must NOT be flagged.
    // The trigger function body is in the routines — not re-tokenized here to avoid duplication.
    // We still check hasPgDynamicSql on the trigger_def itself to be thorough,
    // but the EXECUTE FUNCTION clause will correctly be stripped by hasPgDynamicSql.
    const body = includeBody ? (row.trigger_def ?? undefined) : undefined;

    // Check for dynamic SQL in the trigger def (EXECUTE FUNCTION is NOT dynamic)
    let hasDynSql: boolean | undefined;
    if (body !== undefined) {
      const result = tokenizePgBody(body, []);
      if (result.hasDynamicSql) hasDynSql = true;
    }

    const obj: RawObject = {
      kind: 'trigger',
      schema: row.schema_name,
      name: row.trigger_name,
      trigger: triggerInfo,
      ...(body !== undefined ? { body } : {}),
      ...(hasDynSql !== undefined ? { hasDynamicSql: hasDynSql } : {}),
    };
    return obj;
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Sequence extraction
// ─────────────────────────────────────────────────────────────────────────────

function buildSequences(
  input: PgRowInput,
  scope: ExtractionScope,
): RawObject[] {
  if (scope.levels.sequences === 'off') return [];

  return input.sequences.map((row): RawObject => ({
    kind: 'sequence',
    schema: row.schema_name,
    name: row.sequence_name,
    extra: {
      startValue: row.start_value,
      increment: row.increment,
      minimumValue: row.minimum_value,
      maximumValue: row.maximum_value,
      isCycling: row.is_cycling,
    },
    ...(row.comment !== null ? { comment: row.comment } : {}),
  }));
}

// ─────────────────────────────────────────────────────────────────────────────
// buildPgRawCatalog — main entry point
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Assembles a deterministic RawCatalog from pre-fetched pg_catalog row arrays.
 * Mirrors buildMssqlRawCatalog() from mssql/map.ts in structure and ordering contract.
 *
 * @param input  Pre-fetched pg_catalog rows (from driver in production; from fixtures in tests)
 * @param scope  Resolved extraction scope (levels for each object type)
 */
export function buildPgRawCatalog(
  input: PgRowInput,
  scope: ExtractionScope,
): RawCatalog {
  // Build column name lookup for constraint/index column resolution
  const columnNameMap = buildColumnNameMap(input.columnNames);

  // Build potential deps list for body tokenization (tables + views as dep targets)
  const potentialDeps = [
    ...input.tables.map((t) => ({ schema: t.schema_name, name: t.table_name })),
    ...input.views.map((v) => ({ schema: v.schema_name, name: v.view_name })),
  ];

  // DOG-3 (D5): group the flat view_column_usage rows once, reused by buildViews for every
  // view. Absent input → an empty Map → every view dep stays object grain (byte-identical).
  const viewColumnGroups = groupViewColumnUsage(input.viewColumnUsage ?? []);

  const objects: RawObject[] = [];

  // Tables (always if not 'off')
  objects.push(...buildTables(input, scope, columnNameMap));

  // Views (regular + materialized)
  objects.push(...buildViews(input, scope, potentialDeps, viewColumnGroups));

  // Routines: functions + procedures (each filtered by its own scope level)
  objects.push(...buildRoutines(input, scope));

  // Triggers
  objects.push(...buildTriggers(input, scope));

  // Sequences
  objects.push(...buildSequences(input, scope));

  // Sort deterministically by (kindRank, schema, name) — ADR-008
  objects.sort(compareObjects);

  // Schemas: distinct sorted set from all extracted objects
  // Use input.schemas as primary source (covers schemas with no tables),
  // and supplement with schemas observed in the extracted objects.
  const schemaSet = new Set<string>(input.schemas.map((s) => s.schema_name));
  for (const obj of objects) {
    if (obj.schema !== null) schemaSet.add(obj.schema);
  }

  return {
    engine: 'pg',
    schemas: Array.from(schemaSet).sort(),
    objects,
  };
}
